### ISSUE TITLE
🐞 bug: No colors when trying to use oh-my-zsh theme

### ISSUE THREAD

**Issue by ofirgall** [zdharma-continuum/zinit#189]
### Issue description

I'm trying to migrate to zinit but my oh-my-zsh theme doesn't work, I have tried to use clean `~/.zshrc` with the [NicoSantangelo/Alpharized](https://github.com/nicosantangelo/Alpharized) example but it didn't seems to work, I have no colors.
![zsh](https://user-images.githubusercontent.com/4954051/155836261-81c475d5-5063-46d9-9b80-91a52d38516a.png)

### zinit config

```zsh

### Added by Zinit's installer
if [[ ! -f $HOME/.local/share/zinit/zinit.git/zinit.zsh ]]; then
    print -P "%F{33} %F{220}Installing %F{33}ZDHARMA-CONTINUUM%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$HOME/.local/share/zinit" && command chmod g-rwX "$HOME/.local/share/zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.local/share/zinit/zinit.git" && \
        print -P "%F{33} %F{34}Installation successful.%f%b" || \
        print -P "%F{160} The clone has failed.%f%b"
fi

source "$HOME/.local/share/zinit/zinit.git/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit


## Oh My Zsh Setting
ZSH_THEME="alpharized"

## Zinit Setting
# Must Load OMZ Git library
zinit snippet OMZL::git.zsh

# Load Git plugin from OMZ
zinit snippet OMZP::git
zinit cdclear -q # <- forget completions provided up to this moment

setopt promptsubst

# Load Prompt
zinit light NicoSantangelo/Alpharized

```

### zinit version or commit ID

d1cb4e2b47cee6f298c59b35954f45aba9c26246

### zsh version

5.8

### host info

CPUTYPE=x86_64 MACHTYPE=x86_64 XDG_SESSION_TYPE=x11 OSTYPE=linux-gnu 5.13.0-28-generic VERSION="20.04.3 LTS (Focal Fossa)" ID=ubuntu

**Comment by ofirgall** [comment]
Those are my `alatrcitty` color settings, they are work fine with oh-my-zsh.
```yaml
colors:
  # Default colors
  primary:
    background: '0x000000'
    foreground: '0xffffff'

  normal:
    black: '0x2e3436'
    red: '0xcc0000'
    green: '0x4e9a06'
    yellow: '0xc4a000'
    blue: '0x3465a4'
    magenta: '0x75507b'
    cyan: '0x06989a'
    white: '0xd3d7cf'

  bright:
    black: '0x555753'
    red: '0xef2929'
    green: '0x8ae234'
    yellow: '0xfce94f'
    blue: '0x729fcf'
    magenta: '0xad7fa8'
    cyan: '0x34e2e2'
    white: '0xeeeeec'
```
